apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatgpt-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatgpt
  template:
    metadata:
      labels:
        app: chatgpt
    spec:
      containers:
      - name: chatgpt
        image: gcr.io/ai-brain-382522/ai_brain:latest
        ports:
        - containerPort: 5000
        env:
        - name: MODEL_NAME
          value: "EleutherAI/gpt-neo-1.3B"
        resources:
          limits:
            memory: 15Gi
            cpu: 4
          requests:
            memory: 15Gi
            cpu: 4
